#!/bin/sh

#
# aad-login - calls aad-login.js to authenticate to Azure AD
#   Available under the Apache 2 License
#

# Early in /etc/pam.d/common-auth, add:
#   auth sufficient pam_exec.so expose_authtok /usr/local/bin/aad-login

read password
if [ -n "$password" ]
then
  node /opt/aad-login/aad-login.js $PAM_USER $password
  if [ "$?" -ne "0" ]
  then
    exit 1
  else
    getent passwd $PAM_USER || \
    useradd -m $PAM_USER
    exit 0
  fi
fi
